# Generated by Django 4.2 on 2025-11-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('D', 'Drama'), ('C', 'Comedia'), ('T', 'Terror'), ('A', 'Acción'), ('R', 'Romance'), ('I', 'Infantil')], max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('release_year', models.IntegerField()),
                ('synopsis', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movies/')),
            ],
        ),
    ]
